<h1>Login</h1>
<form action="<?php echo URL; ?>/auth/login" method="post">
    <div class="col-md-3">
        <label>Email</label><input class="form-control" type="text" name="email"/>
    </div>
    <div class="col-md-3">
        <label>Password</label><input class="form-control" type="password" name="password"/>
    </div>
    <div class="form-actions fluid">
        <input type="submit" value="Log in"/>
    </div>
</form>

<a href="<?php echo URL; ?>/auth/reset/">Forgotten your password?</a>