<h1>Courses</h1>
<?php if ($this->success === 1) : ?>
    <p>Course added successfully</p>
<?php endif ?>
<a href="<?php echo URL; ?>/admin/courses/add">Add Course</a>
<div class="table-widget">
    <table class="table table-striped table-bordered table-advance table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->courses as $course) : ?>
            <tr id="<?php echo $course['id']; ?>">
                <td><?php echo $course['id']; ?></td>
                <td><?php echo $course['name']; ?></td>
                <td><?php echo $course[4]; ?></td>
                <td><?php echo $course['description']; ?></td>
                <td><a class="table-delete" href="#_">Delete</a><i class="fa fa-trash"></i> /
                <a href="<?php echo URL; ?>/admin/courses/edit/<?php echo $course['id']; ?>">Edit</a><i class="fa fa-trash"></i></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    /*****************************************
     * DELETE comment
     *****************************************/
    $(document).ready(function () {
        $('.table-delete').on('click', function(){
            var c = confirm('Are you sure you want to DELETE this comment?');
            if(c == true){
                var id = $(this).closest('tr').attr('id');
                var table = 'comment';
                $.ajax({
                    url: "/admin/ajax/delete",
                    data: {id : id, table : table},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
                $(this).closest('tr').fadeOut(1000);
            }
        });
    });

    /*****************************************
     * BULK DELETE product
     *****************************************/
    $('.bulk-delete').on('click', function(){
        var action = $('#bulk-actions option:selected').text();
        if (action == 'Delete') {
            var c = confirm('Are you sure you want to DELETE the selected comment(s)?');
            if(c == true){
                var id = [];
                $(':checkbox:checked').each(function(i){
                    id[i] = $(this).val();
                    //Set the table here, this is the only difference between each ajax delete
                    var table = 'comment';
                    $.ajax({
                        async: false,
                        url: "/admin/ajax/delete",
                        data: {id : id[i], table : table},
                        dataType: "json",
                        type: "POST",
                        success: function(data){
                            response(data);
                        }
                    });
                });
                $(':checkbox:checked').each(function(i){
                    $(this).closest('tr').fadeOut(1000);
                });
            }
        }
    });
</script>

