<h1>Edit your details</h1>
<form id="account" action="<?php echo URL; ?>/account/" method="post">
    <input type="text" value="<?php echo $this->account[0]['first_name']; ?>" name="first-name" placeholder="First Name*">
    <input type="text" value="<?php echo $this->account[0]['last_name']; ?>" name="last-name" placeholder="Last Name*">
    <input type="text" value="<?php echo $this->account[0]['company']; ?>" name="company" placeholder="Company">
    <input type="email" value="<?php echo $this->account[0]['email']; ?>" name="email" placeholder="Email address*">
    <input type="submit" value="Update">
</form>


