<div class="row">
    <div class="col-md-9">
        <a href="<?php echo URL; ?>/courses/view/<?php echo $this->course['id']; ?>"><?php echo $this->course['name']; ?></a>
        <img src="<?php echo URL; ?>/public/images/<?php echo $this->course['image']; ?>"/>
        <?php echo $this->course['description']; ?>
        <?php echo $this->course['price']; ?>
        <?php echo $this->course['no_of_videos']; ?>
    </div>
    <div class="col-md-3">
        <h1>Subscribe</h1>
        <form action="" method="POST">
            <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="pk_test_CeMyfzmPBnaYxxa8JyRIu2R4"
                data-amount="2500"
                data-name="Playground"
                data-description="Ultimate PHP for Beginner's ($25.00)"
                data-image="/128x128.png">
            </script>
        </form>
    </div>
</div>


