<div class="row">
    <h1><?php echo $this->category['name']; ?></h1>
    <?php foreach ($this->courses as $course) : ?>
        <div class="col-md-3">
            <h3><a href="<?php echo URL; ?>/courses/view/<?php echo $course['id']; ?>"><?php echo $course['name']; ?></a></h3>
            <p><?php echo $course['description']; ?></p>
            <p>&pound;<?php echo $course['price']; ?></p>
        </div>
    <?php endforeach; ?>
</div>