<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Number of Videos</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><a href="<?php echo URL; ?>/courses/view/<?php echo $this->course['id']; ?>"><?php echo $this->course['name']; ?></a></td>
        <td><?php echo $this->course['description']; ?></td>
        <td><?php echo $this->course['price']; ?></td>
        <td><?php echo $this->course['no_of_videos']; ?></td>
        <?php if ($this->is_subscribed === true) : ?>
            <td>Subscribed</td>
        <?php else: ?>
            <td><a href="<?php echo URL; ?>">Subscribe</a></td>
        <?php endif; ?>
    </tr>
    </tbody>
</table>


