<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Number of Videos</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->courses as $course) : ?>
        <tr>
            <td><a href="<?php echo URL; ?>/courses/view/<?php echo $course['id']; ?>"><?php echo $course['name']; ?></a></td>
            <td><?php echo $course['description']; ?></td>
            <td><?php echo $course['price']; ?></td>
            <td><?php echo $course['no_of_videos']; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


