</div>
</div>
</div>

<div id="footer">
</div>
<script>
    $(document).ready(function () {
        $(".side-list").on("click", function (e) {
            $(this).siblings().removeClass("active");
            $(this).addClass("active");
        });
        var pathname = window.location.pathname;
        var pathArray = pathname.split("/");
        var lastEl = pathArray[pathArray.length-1];
        if (lastEl)
        {
            $("#"+lastEl).find("i").last().removeClass().addClass("fa fa-chevron-down");
            $("#"+lastEl).addClass("active");
        }
    });
</script>
</body>

</html>
