</div>
</div>
</div>

<div id="footer">
</div>
<script>
    $(document).ready(function () {
        $(".side-list").on("click", function (e) {
            $(this).siblings().removeClass("active");
            $(this).addClass("active");
            $.cookie("a",this.id);
        });
        var a = $.cookie("a");
        if (a) {
            $("#"+a).find("i").last().removeClass().addClass("fa fa-chevron-down");
            $("#"+a).addClass("active");
        }
    });
</script>
</body>

</html>
