<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <!-- Font awesome -->
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>/public/css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>/public/css/admin.css"/>
    <script type="text/javascript" src="<?php echo URL; ?>/public/js/custom.js"></script>
    <script src="<?php echo URL; ?>/public/Chart.js/Chart.js"></script>
    <script src="<?php echo URL; ?>/public/jquery-cookie/jquery.cookie.js"></script>
    <!-- Place inside the <head> of your HTML -->
    <script type="text/javascript" src="<?php echo URL; ?>/vendor/tinymce/js/tinymce/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea"
        });
    </script>


</head>
<body>

<div id="header">
    <div class="page-title">
        <h1 class="title">Playground Admin Panel</h1>
    </div>
    <div class="page-top-menu">
        <ul class="nav navbar-nav pull-right">
            <li class="nav-dropdown-top dropdown-user">
                <a href="#"><img class="img-circle" src="" alt="">
                    <span class="username"><?php echo $this->user['first_name']; ?></span>
                    <i class="fa fa-angle-down"></i>
                </a>
            </li>
            <li class="nav-dropdown-top">
                <a class="sign-out-top" href="/auth/logout/"><i class="fa fa-sign-out"></i></a>
            </li>
        </ul>
    </div>
</div>

<div class="page-container">
        <div class="admin-sidebar navbar-collapse collapse">
            <nav id="admin-nav">
                <ul>
                    <li class="searchbar">
                        <form class="searchbar-side">
                            <div class="input-group">
                                <input class="form-control search-box" type="text" placeholder="Search...">
                            </div>
                        </form>
                    </li>
                    <li id="1" class="side-list"><a href="/admin"><i class="fa fa-tachometer"></i> Dashboard <i class="fa fa-chevron-left"></i></a>
                    <li id="2" class="side-list"><a href="/admin/categories"><i class="fa fa-list"></i> Categories <i class="fa fa-chevron-left"></i></a>
                    <li id="3" class="side-list"><a href="/admin/courses"><i class="fa fa-book"></i> Courses <i class="fa fa-chevron-left"></i></a>
                    <li id="4" class="side-list"><a href="/admin/topics"><i class="fa fa-pencil"></i> Topics <i class="fa fa-chevron-left"></i></a>
                    <li id="5" class="side-list"><a href="/admin/users"><i class="fa fa-group"></i> Users <i class="fa fa-chevron-left"></i></a>
                </ul>
            </nav>
        </div>
        <div class="content-right">