<div class="row">
    <div class="col-md-12">
        <h1>Subscribed Courses</h1>
        <?php foreach ($this->subscribedCourses as $sc) : ?>
            <a href="<?php echo URL; ?>/courses/view/<?php echo $sc['id']; ?>"><?php echo $sc['name']; ?></a>
            <img src="<?php echo URL; ?>/public/images/<?php echo $sc['image']; ?>"/>
            <?php echo $sc['description']; ?>
            <?php echo $sc['price']; ?>
            <?php echo $sc['no_of_videos']; ?>
        <?php endforeach; ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h1>Available Courses</h1>
        <?php foreach ($this->availableCourses as $ac) : ?>
            <a href="<?php echo URL; ?>/courses/view/<?php echo $ac['id']; ?>"><?php echo $ac['name']; ?></a>
            <img src="<?php echo URL; ?>/public/images/<?php echo $ac['image']; ?>"/>
            <?php echo $ac['description']; ?>
            <?php echo $ac['price']; ?>
            <?php echo $ac['no_of_videos']; ?>
        <?php endforeach; ?>
    </div>
</div>