<div class="row">
    <?php foreach ($this->results as $result) : ?>
        <div class="col-md-3">
            <a href="<?php echo URL; ?>/courses/view/<?php echo $result['id']; ?>">
                <img src="<?php echo URL; ?>/public/images/<?php echo $result['image']; ?>" width="250" height="200"/>
            </a>
            <?php echo $result['description']; ?>
        </div>
    <?php endforeach; ?>
</div>