<h1>Courses</h1>
<?php if ($this->success === 1) : ?>
    <p>Course added successfully</p>
<?php endif ?>
<a href="<?php echo URL; ?>/admin/courses/add">Add Course</a>
<div class="table-widget">
    <table class="table table-striped table-bordered table-advance table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->courses as $course) : ?>
            <tr id="<?php echo $course['id']; ?>">
                <td><a href="<?php echo URL; ?>/admin/courses/edit/<?php echo $course['id']; ?>"><?php echo $course['name']; ?></a></td>
                <td><?php echo $course['description']; ?></td>
                <td><a class="delete-course" href="#_">Delete</a><i class="fa fa-trash"></i></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    /*****************************************
     * DELETE course
     *****************************************/
    $(document).ready(function () {
        $('.delete-course').on('click', function(){
            var c = confirm('Are you sure you want to DELETE this course?');
            if(c == true){
                var courseid = $(this).closest('tr').attr('id');
                $.ajax({
                    url: "/admin/ajax/deletecourse",
                    data: {courseid : courseid},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
                $(this).closest('tr').fadeOut(1000);
            }
        });
    });

    /*****************************************
     * BULK DELETE product
     *****************************************/
    $('.bulk-delete').on('click', function(){
        var action = $('#bulk-actions option:selected').text();
        if (action == 'Delete') {
            var c = confirm('Are you sure you want to DELETE the selected vendor product(s)?');
            if(c == true){
                var productid = [];
                $(':checkbox:checked').each(function(i){
                    productid[i] = $(this).val();
                    $.ajax({
                        async: false,
                        url: "/admin/ajax/delete-vendor-products",
                        data: {productid : productid[i]},
                        dataType: "json",
                        type: "POST",
                        success: function(data){
                            response(data);
                        }
                    });
                });
                $(':checkbox:checked').each(function(i){
                    $(this).closest('tr').fadeOut(1000);
                });
            }
        }
    });
</script>

