<div class="row">
    <div class="col-md-12">
        <h1>Edit Course</h1>
        <ul class="breadcrumbs-list">
            <li>
                <i class="fa fa-home"></i>
                <a href="index.html">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Dashboard</a>
            </li>
            <li class="pull-right">
                <div id="dashboard-report-range" class="dashboard-date-range tooltips" data-original-title="Change dashboard date range" data-placement="top" style="display: block;">
                    <i class="fa fa-calendar"></i>
                    <span><?php echo date('l jS F Y'); ?></span>
                    <i class="fa fa-angle-down"></i>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="" method="post">
            <div class="form-body">
                <div class="form-group">
                    <input class="form-control" type="hidden" value="<?php echo $this->user['id']; ?>" name="id">
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">First Name <span class="required"> * </span></label>
                    <input class="form-control" type="text" value="<?php echo $this->user['first_name']; ?>" name="first-name">
                </div>
                <div class="form-group">
                    <label class=" col-md-3 control-label">Last Name <span class="required"> * </span></label>
                    <input class="form-control" type="text" value="<?php echo $this->user['last_name']; ?>" name="last-name">
                </div>
                <div class="form-group">
                    <label class=" col-md-3 control-label">Role <span class="required"> * </span></label>
                    <select class="table-group-action-input form-control input-medium" name="role">
                        <option <?php echo ($this->user['role'] == 'default')?"selected":""; ?> value="false">Default</option>
                        <option <?php echo ($this->user['role'] == 'admin')?"selected":""; ?> value="true">Admin</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class=" col-md-3 control-label">Age <span class="required"> * </span></label>
                    <select class="table-group-action-input form-control input-medium" name="age">
                        <option <?php echo ($this->user['is_over_13'] == 'false')?"selected":""; ?> value="false">Below 13</option>
                        <option <?php echo ($this->user['is_over_13'] == 'true')?"selected":""; ?> value="true">Above 13</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class=" col-md-3 control-label">Email <span class="required"> * </span></label>
                    <input class="form-control" type="email" value="<?php echo $this->user['email']; ?>" name="email">
                </div>
                <div class="form-actions fluid">
                    <button class="btn blue" type="submit">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>