<?php if ($this->success === 1) : ?>
    <p>User added successfully</p>
<?php endif ?>
<a href="<?php echo URL; ?>/admin/users/add">Add a new user</a>
<div class="table-widget">
    <table class="table table-striped table-bordered table-advance table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Number of Videos</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->users as $user) : ?>
            <tr id="<?php echo $user['id']; ?>">
                <td><a href="<?php echo URL; ?>/admin/users/edit/<?php echo $user['id']; ?>"><?php echo $user['first_name'] . ' ' . $user['last_name']; ?></a></td>
                <td><?php echo $user['email']; ?></td>
                <td><?php echo $user['role']; ?></td>
                <td><?php echo $user['company']; ?></td>
                <td><a class="delete-user" href="#_">Delete</a><i class="fa fa-trash"></i></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    /*****************************************
     * DELETE user
     *****************************************/
    $(document).ready(function () {
        $('.delete-user').on('click', function(){
            var c = confirm('Are you sure you want to DELETE this user?');
            if(c == true){
                var userid = $(this).closest('tr').attr('id');
                $.ajax({
                    url: "/admin/ajax/deleteuser",
                    data: {userid : userid},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
                $(this).closest('tr').fadeOut(1000);
            }
        });
    });

    /*****************************************
     * BULK DELETE product
     *****************************************/
    $('.bulk-delete').on('click', function(){
        var action = $('#bulk-actions option:selected').text();
        if (action == 'Delete') {
            var c = confirm('Are you sure you want to DELETE the selected vendor product(s)?');
            if(c == true){
                var productid = [];
                $(':checkbox:checked').each(function(i){
                    productid[i] = $(this).val();
                    $.ajax({
                        async: false,
                        url: "/admin/ajax/delete-vendor-products",
                        data: {productid : productid[i]},
                        dataType: "json",
                        type: "POST",
                        success: function(data){
                            response(data);
                        }
                    });
                });
                $(':checkbox:checked').each(function(i){
                    $(this).closest('tr').fadeOut(1000);
                });
            }
        }
    });
</script>

