<h1>Add Topic</h1>
<div class="col-md-6">
    <form action="" method="post">
        <div class="form-body">
            <div class="form-group">
                <label class=" control-label">Topic Name</label>
                <input class="form-control" type="text" name="name">
            </div>
            <div class="form-group">
                <label class="control-label">Difficulty</label>
                <input class="form-control" type="text" name="difficulty">
            </div>
            <div class="form-group">
                <label class="control-label">Description</label>
                <input class="form-control" type="text" name="description">
            </div>
            <div class="form-group">
                <label class="control-label">Content</label>
                <textarea class="form-control" name="content">
                </textarea>
            </div>
            <div class="form-actions fluid">
                <button class="btn blue" type="submit">Submit</button>
            </div>
        </div>
    </form>
</div>


