<h1>Add Category</h1>
<div class="col-md-6">
    <form action="" method="post">
        <div class="form-body">
            <div class="form-group">
                <label class=" control-label">Category Name</label>
                <input class="form-control" type="text" name="name">
            </div>
            <div class="form-actions fluid">
                <button class="btn blue" name="Submit" type="submit">Submit</button>
            </div>
        </div>
    </form>
</div>