<div class="row">
    <div class="col-md-12">
        <h1>Edit Course</h1>
        <ul class="breadcrumbs-list">
            <li>
                <i class="fa fa-home"></i>
                <a href="index.html">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Dashboard</a>
            </li>
            <li class="pull-right">
                <div id="dashboard-report-range" class="dashboard-date-range tooltips" data-original-title="Change dashboard date range" data-placement="top" style="display: block;">
                    <i class="fa fa-calendar"></i>
                    <span><?php echo date('l jS F Y'); ?></span>
                    <i class="fa fa-angle-down"></i>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="" method="post">
            <div class="form-body">
                <form id="register" action="<?php echo URL; ?>/admin/categories/edit" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" value="<?php echo $category['id']; ?>" name="id">
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Category Name <span class="required"> * </span></label>
                        <input class="form-control" type="text" value="<?php echo $category['name']; ?>" name="name">
                    </div>
                    <div class="form-actions fluid">
                        <button class="btn blue" type="submit">Save</button>
                    </div>
                </form>
            </div>
        </form>
    </div>
</div>