<h1>Categories</h1>
<?php if (isset($this->success)) : ?>
    <p>Course added successfully</p>
<?php endif ?>
<a href="<?php echo URL; ?>/admin/categories/add">Add Category</a>
<div class="table-widget">
        <table class="table table-striped table-bordered table-advance table-hover">
            <thead>
            <tr>
                <th>Name</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->categories as $category) : ?>
                <tr id="<?php echo $category['id']; ?>">
                    <td><a href="<?php echo URL; ?>/admin/categories/edit/<?php echo $category['id']; ?>"><?php echo $category['name']; ?></a></td>
                    <td><a class="delete-category" href="#_">Delete</a><i class="fa fa-trash"></i></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
</div>
<script>
    /*****************************************
     * DELETE category
     *****************************************/
    $(document).ready(function () {
        $('.delete-category').on('click', function(){
            var c = confirm('Are you sure you want to DELETE this category?');
            if(c == true){
                var categoryid = $(this).closest('tr').attr('id');
                $.ajax({
                    url: "/admin/ajax/deletecategory",
                    data: {categoryid : categoryid},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
                $(this).closest('tr').fadeOut(1000);
            }
        });
    });

    /*****************************************
     * BULK DELETE category
     *****************************************/
    $('.bulk-delete').on('click', function(){
        var action = $('#bulk-actions option:selected').text();
        if (action == 'Delete') {
            var c = confirm('Are you sure you want to DELETE the selected vendor product(s)?');
            if(c == true){
                var productid = [];
                $(':checkbox:checked').each(function(i){
                    productid[i] = $(this).val();
                    $.ajax({
                        async: false,
                        url: "/admin/ajax/delete-vendor-products",
                        data: {productid : productid[i]},
                        dataType: "json",
                        type: "POST",
                        success: function(data){
                            response(data);
                        }
                    });
                });
                $(':checkbox:checked').each(function(i){
                    $(this).closest('tr').fadeOut(1000);
                });
            }
        }
    });
</script>

