<h1>Users</h1>
<?php if (isset($this->success)) : ?>
    <p>User added successfully</p>
<?php endif ?>
<a class="add-new-button" href="<?php echo URL; ?>/admin/users/add">Add a new user</a>

<form class="form-inline">
    <select class="bulk-actions form-control input-medium">
        <option value="bulk-actions">Bulk Actions</option>
        <option value="delete">Delete</option>
    </select>
    <div class="form-actions fluid">
        <button class="bulk-delete btn blue" type="submit">Apply</button>
    </div>
</form>

<div class="table-widget">
    <table class="table table-striped table-bordered table-advance table-hover">

        <thead>
        <tr>
            <th style="width: 2%"><input class="select-all" value="all" type="checkbox"></th>
            <th>ID</th>
            <th style="width: 50%">Name</th>
            <th style="width: 30%">Email</th>
            <th style="width: 20%">Role</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($this->paginator->data as $user) : ?>
            <tr id="<?php echo $user['id']; ?>">
                <td><input class="checkbox" value="<?php echo $user['id']; ?>" type="checkbox"></td>
                <td><?php echo $user['id']; ?></td>
                <td>
                    <a href="<?php echo URL; ?>/admin/users/edit/<?php echo $user['id']; ?>"><?php echo $user['first_name'] . ' ' . $user['last_name']; ?></a>
                    <a class="table-delete" href="#_">Delete</a>
                </td>
                <td><?php echo $user['email']; ?></td>
                <td><?php echo $user['role']; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>

    </table>
</div>

<div class="paginator">
    <?php foreach ($this->paginator->pages as $pages) : ?>
        <?php echo $pages; ?>
    <?php endforeach; ?>
</div>

<script>
    $(document).ready(function () {
        /*****************************************
         * SELECT ALL
         * ***************************************/
        $('.select-all').click(function() {
            var c = this.checked;
            $('.checkbox').prop('checked', c);
        });

        /*****************************************
         * On hover show delete
         * ***************************************/
        $("tr").on("mouseover", function () {
            $(this).find(".table-delete").addClass("table-delete-active");
        });
        $("tr").on("mouseout", function () {
            $(this).find(".table-delete").removeClass("table-delete-active");
        });

        /*****************************************
         * DELETE user
         *****************************************/
        $('.delete-user').on('click', function(){
            var c = confirm('Are you sure you want to DELETE this user?');
            if(c == true){
                var userid = $(this).closest('tr').attr('id');
                $.ajax({
                    url: "/admin/ajax/deleteuser",
                    data: {userid : userid},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
                $(this).closest('tr').fadeOut(1000);
            }
        });
    });

    /*****************************************
     * BULK DELETE user
     *****************************************/
    $('.bulk-delete').on('click', function(){
        var action = $('#bulk-actions option:selected').text();
        if (action == 'Delete') {
            var c = confirm('Are you sure you want to DELETE the selected vendor product(s)?');
            if(c == true){
                var productid = [];
                $(':checkbox:checked').each(function(i){
                    productid[i] = $(this).val();
                    $.ajax({
                        async: false,
                        url: "/admin/ajax/delete-vendor-products",
                        data: {productid : productid[i]},
                        dataType: "json",
                        type: "POST",
                        success: function(data){
                            response(data);
                        }
                    });
                });
                $(':checkbox:checked').each(function(i){
                    $(this).closest('tr').fadeOut(1000);
                });
            }
        }
    });
</script>

