<div class="page-header">
    <h1><?php echo $this->topic['name']; ?></h1>
</div>
<?php if (isset($this->success)) : ?>
    <div class="alert-fade alert alert-success">
        <?php echo $this->success; ?>
    </div>
<?php endif; ?>
<h5><?php echo $this->topic['description']; ?></h5>
<p>
    <em>by <a class="author" href="#"><?php echo $this->topic['author']; ?></a>
        <?php echo @date('j F Y', strtotime($this->topic['added'])); ?>
         <a class="total-comments" href="#comments"><i class="fa fa-comment"></i> <?php echo $this->totalComments ?> comments</a></em>
</p>


<p><?php echo $this->topic['content']; ?></p>
<!--<video width="400" height="320" controls>
    <source src="https://www.youtube.com/watch?feature=player_detailpage&v=uUV-K7ggTjc" type="video/mp4">
    <source src="https://www.youtube.com/watch?feature=player_detailpage&v=uUV-K7ggTjc" type="video/ogg">
</video>-->

<div class="page-header">
    <span><h4>Ready to level?</h4> <a href="/topics/codepass/<?php echo $this->topic['id']; ?>">Take the Code Pass.</a></span>
</div>

<div id="comments" class="comments-section">
    <h4>Comments</h4>
    <form action="" method="post">
        <div class="form-group">
            <textarea class="form-control comments-box" name="comment" placeholder="Reply to this post..."></textarea>
            <div class="form-actions fluid">
                <input class="btn" type="submit" value="Submit">
            </div>
        </div>
    </form>

    <!-- Parent comments section -->
    <?php if (empty($this->comments)) : ?>
        <p>No comments have been posted yet.</p>
    <?php endif; ?>
    <?php foreach ($this->comments as $comment) : ?>
        <div class="comment-wrapper">
            <div class="comment-image">
                <?php if (is_null($comment['avatar'])) : ?>
                    <img src="<?php echo URL; ?>/public/images/noavatar.png">
                <?php else : ?>
                    <img src="<?php echo $comment['avatar'] ?>">
                <?php endif; ?>
            </div>
            <div class="comment-header">
                <a href="/profile/view/<?php echo $comment['username']; ?>" class="comment-user"><?php echo $comment['username'] ?></a>
                <?php echo $comment['created']; ?>
            </div>

            <p><?php echo $comment['comment']; ?></p>
            <span id="<?php echo $comment[0]; ?>">
                <a class="up-votes" href="#_" title="<?php echo $comment['votes_up'];?> up votes"><?php echo $comment['votes_up'];?> <i class="fa fa-angle-up"></i></a>
                <a class="down-votes" href="#_" title="<?php echo $comment['votes_down']; ?> down votes"><?php echo $comment['votes_down']; ?> <i class="fa fa-angle-down"></i></a>
            </span>
            <span>
            <?php if ($this->user['username'] == $comment['username']) : ?>
                <a class="delete-comment" href="#_">Delete</a>
            <?php endif; ?>
                <a class="comment-reply">Reply</a>
            </span>
            <form class="<?php echo $comment['id']; ?>-form with-parent" action="" method="post">
                <div class="form-group">
                    <input class="form-control" type="hidden" name="parent" value="<?php echo $comment[0]; ?>">
                    <textarea class="form-control comments-box" name="comment-reply" placeholder="Reply to this comment..."></textarea>
                </div>
                <div class="form-actions fluid">
                    <input class="btn" type="submit" value="Submit">
                </div>
            </form>
        </div>
        <!-- End parent comments -->

        <!-- Child comments section -->
        <div class="child-comments">
            <?php foreach ($this->childComments as $childComments) : ?>
                <?php foreach ($childComments as $childComment) : ?>
                    <?php if ($comment[0] == $childComment['parent']) : ?>
                        <div class="comment-wrapper">

                            <div class="comment-image">
                                <?php if (is_null($comment['avatar'])) : ?>
                                    <img src="<?php echo URL; ?>/public/images/noavatar.png">
                                <?php else : ?>
                                    <img src="<?php echo $comment['avatar'] ?>">
                                <?php endif; ?>
                            </div>

                            <div class="comment-header">
                                <a href="/profile/view/<?php echo $comment['username']; ?>" class="comment-user"><?php echo $childComment['username']; ?></a>
                                <?php echo $childComment['created']; ?>
                            </div>

                            <p><?php echo $childComment['comment']; ?></p>
                            <!-- Votes -->
                            <span id="<?php echo $childComment[0]; ?>" class="votes">
                                <a class="up-votes" href="#_" title="<?php echo $childComment['votes_up']; ?> up votes">
                                    <?php echo $childComment['votes_up'];?> <i class="fa fa-angle-up"></i></a>
                                <a class="down-votes" href="#_" title="<?php echo $childComment['votes_down']; ?> down votes">
                                    <?php echo $childComment['votes_down']; ?> <i class="fa fa-angle-down"></i></a>
                            </span>
                            <!-- End votes -->
                            <span>
                            <?php if ($this->user['username'] == $childComment['username']) : ?>
                                <a class="delete-comment" href="#_">Delete</a>
                            <?php endif; ?>
                                <a class="comment-reply">Reply</a>
                            </span>

                            <form class="<?php echo $childComment['id']; ?>-form with-parent" action="" method="post">
                                <div class="form-group">
                                    <input type="hidden" name="parent" value="<?php echo $childComment['id']; ?>">
                                    <textarea class="form-control comments-box" name="comment-reply" placeholder="Reply to this comment..."></textarea>
                                </div>
                                <div class="form-actions fluid">
                                    <input class="btn" type="submit" value="Submit">
                                </div>
                            </form>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </div>
        <!-- End child comments -->
    <?php endforeach; ?>
</div>

<script>
    $(document).ready(function () {

        $(".alert-fade").delay(3000).fadeOut("slow");

        $(".comment-reply").on("click", function () {
            $(this).parent().next("form").toggle();
        });

        $(".up-votes").on("click", function () {
            var id = $(this).closest('span').attr('id');
            var a = $(this);
            $.ajax({
                url: "/topics/upvote",
                data: {id : id},
                type: "POST",
                success: function(data, status, xhr) {
                    if(data == 'true')
                    {
                        $(a).html( function(i, oldval) {
                            var newVal = parseInt( oldval, 10) + 1;
                            return newVal + " <i class='fa fa-angle-up'></i>";
                        });
                    }
                    else if (data == 'false')
                    {
                        alert('You have already voted on this comment');
                    }
                    else if (data == 'Not logged in')
                    {
                        alert('You need to be logged in to vote')
                    }
                }
            });
        });

        $(".down-votes").on("click", function () {
            var id = $(this).closest('span').attr('id');
            var a = $(this);
            $.ajax({
                url: "/topics/downvote",
                data: {id : id},
                type: "POST",
                success: function(data, status, xhr) {
                    if(data == 'true')
                    {
                        $(a).html( function(i, oldval) {
                            var newVal = parseInt( oldval, 10) + 1;
                            return newVal + " <i class='fa fa-angle-down'></i>";
                        });
                    }
                    else if (data == 'false')
                    {
                        alert('You have already voted on this comment');
                    }
                    else if (data == 'Not logged in')
                    {
                        alert('You need to be logged in to vote')
                    }
                }
            });
        });
    });
</script>


