<h1>Add Course</h1>
<div class="col-md-6">
    <form action="" method="post">
        <div class="form-body">
            <div class="form-group">
                <label class=" control-label">Course Name</label>
                <input class="form-control" type="text" name="name">
            </div>
            <div class="form-group">
                <label class="control-label">Description</label>
                <input class="form-control" type="text" name="description">
            </div>
            <div class="form-group">
                <label class="control-label">Course</label>
                <select class="form-control" name="category">
                    <?php foreach ($this->categories as $category) : ?>
                        <option value="<?php echo $category['id']; ?>"><?php echo $category['name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-actions fluid">
                <button class="btn blue" type="submit">Submit</button>
            </div>
        </div>
    </form>
</div>


