<h1>Courses</h1>
<?php if (isset($this->success)) : ?>
    <p>Course added successfully</p>
<?php endif ?>
<a class="add-new-button" href="<?php echo URL; ?>/admin/courses/add">Add Course</a>

<form class="form-inline">
    <select class="bulk-actions form-control input-medium">
        <option value="bulk-actions">Bulk Actions</option>
        <option value="delete">Delete</option>
    </select>
    <div class="form-actions fluid">
        <button class="bulk-delete btn blue" type="submit">Apply</button>
    </div>
</form>

<div class="table-widget">
    <table class="table table-striped table-bordered table-advance table-hover">
        <thead>
        <tr>
            <th style="width: 2%"><input class="select-all" value="all" type="checkbox"></th>
            <th style="width: 5%">ID</th>
            <th style="width: 30%">Name</th>
            <th>Category</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->courses as $course) : ?>
            <tr id="<?php echo $course['id']; ?>">
                <td><input class="checkbox" value="<?php echo $course['id']; ?>" type="checkbox"></td>
                <td><?php echo $course['id']; ?></td>
                <td>
                    <a href="<?php echo URL; ?>/admin/courses/edit/<?php echo $course['id']; ?>"><?php echo $course['name']; ?></a>
                    <a class="table-delete" href="#_">Delete</a>
                </td>
                <td><?php echo $course[4]; ?></td>
                <td><?php echo $course['description']; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        /*****************************************
         * SELECT ALL
         * ***************************************/
        $('.select-all').click(function() {
            var c = this.checked;
            $('.checkbox').prop('checked', c);
        });

        /*****************************************
         * On hover show delete
         * ***************************************/
        $("tr").on("mouseover", function () {
            $(this).find(".table-delete").addClass("table-delete-active");
        });
        $("tr").on("mouseout", function () {
            $(this).find(".table-delete").removeClass("table-delete-active");
        });
        /*****************************************
         * DELETE course
         *****************************************/
        $('.table-delete').on('click', function(){
            var c = confirm('Are you sure you want to DELETE this course?');
            if(c == true){
                var id = $(this).closest('tr').attr('id');
                //Set the table here, this is the only difference between each ajax delete
                var table = 'course';
                $.ajax({
                    url: "/admin/ajax/delete",
                    data: {id : id, table : table},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
                $(this).closest('tr').fadeOut(1000);
            }
        });
    });

    /*****************************************
     * BULK DELETE product
     *****************************************/
    $('.bulk-delete').on('click', function(){
        var action = $('#bulk-actions option:selected').text();
        if (action == 'Delete') {
            var c = confirm('Are you sure you want to DELETE the selected course(s)?');
            if(c == true){
                var id = [];
                $(':checkbox:checked').each(function(i){
                    id[i] = $(this).val();
                    //Set the table here, this is the only difference between each ajax delete
                    var table = 'course';
                    $.ajax({
                        async: false,
                        url: "/admin/ajax/delete",
                        data: {id : id[i], table : table},
                        dataType: "json",
                        type: "POST",
                        success: function(data){
                            response(data);
                        }
                    });
                });
                $(':checkbox:checked').each(function(i){
                    $(this).closest('tr').fadeOut(1000);
                });
            }
        }
    });
</script>

